apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  source:
    repoURL: https://github.com/ygtkync/awsproject-1.git
    targetRevision: main
    path: apps/online-boutique       # kustomize overlay'imiz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
