apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true      
      selfHeal: true  
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: "*"
    helm:
      valuesObject:
        server:
          
          persistentVolume: { enabled: false }
          retention: 24h
          service: { port: 80 }
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.yigitaws.xyz
            paths:
              - /
            pathType: Prefix
        alertmanager:
          enabled: false
        prometheus-pushgateway:
          enabled: false
        kube-state-metrics:
          enabled: false
        prometheus-node-exporter:
          enabled: true
