apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: "*"
    helm:
      valuesObject:
        server:
          persistentVolume: { enabled: false }   # PVC/CSI uğraştırmasın
          retention: 24h
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 500m, memory: 512Mi }
          service: { port: 80 }
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /
            pathType: Prefix
            hosts: [ "prometheus.yigitaws.xyz" ]

        # DİĞER BİLEŞENLERİ KAPAT
        alertmanager:
          enabled: false

        prometheus-pushgateway:
          enabled: false

        kube-state-metrics:
          enabled: false

        prometheus-node-exporter:
          enabled: true
          resources:
            requests: { cpu: 10m, memory: 32Mi }
            limits:   { cpu: 100m, memory: 128Mi }
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
